"""portland

Revision ID: 67a4ee6196bc
Revises: 
Create Date: 2021-07-29 14:55:45.745407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a4ee6196bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('econ_fulltext',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_econ_fulltext_id'), 'econ_fulltext', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_econ_fulltext_id'), table_name='econ_fulltext')
    op.drop_table('econ_fulltext')
    # ### end Alembic commands ###
